class Runner {

	public static void main(String[] args) {

		NoteBook noteBook1 = new NoteBook();

		System.out.println("id :" + noteBook1.id);
		System.out.println("company :" + noteBook1.company);
		System.out.println("size :" + noteBook1.size);
		System.out.println("type :" + noteBook1.type);
		System.out.println("quality :" + noteBook1.quality);
		System.out.println("isline :" + noteBook1.isline);
		System.out.println("waterProof :" + noteBook1.waterProof);
		System.out.println("weight :" + noteBook1.weight);
		System.out.println("width :" + noteBook1.width);
		System.out.println("length :" + noteBook1.length);
		System.out.println("noOfPages :" + noteBook1.noOfPages);
		System.out.println("origin :" + noteBook1.origin);
		System.out.println("price :" + noteBook1.price);
		System.out.println("shape :" + noteBook1.shape);
		System.out.println("availability :" + noteBook1.availability);
		System.out.println("isMargin :" + noteBook1.isMargin);
		System.out.println("paperMaterial :" + noteBook1.paperMaterial);
		System.out.println("spiral :" + noteBook1.spiral);
		System.out.println("usage :" + noteBook1.usage);
		System.out.println("coverMaterial :" + noteBook1.coverMaterial);
		System.out.println(noteBook1);
		System.out.println("\n");

		NoteBook noteBook2 = new NoteBook();

		System.out.println("id :" + noteBook2.id);
		System.out.println("company :" + noteBook2.company);
		System.out.println("size :" + noteBook2.size);
		System.out.println("type :" + noteBook2.type);
		System.out.println("quality :" + noteBook2.quality);
		System.out.println("isline :" + noteBook2.isline);
		System.out.println("waterProof :" + noteBook2.waterProof);
		System.out.println("weight :" + noteBook2.weight);
		System.out.println("width :" + noteBook2.width);
		System.out.println("length :" + noteBook2.length);
		System.out.println("noOfPages :" + noteBook2.noOfPages);
		System.out.println("origin :" + noteBook2.origin);
		System.out.println("price :" + noteBook2.price);
		System.out.println("shape :" + noteBook2.shape);
		System.out.println("availability :" + noteBook2.availability);
		System.out.println("isMargin :" + noteBook2.isMargin);
		System.out.println("paperMaterial :" + noteBook2.paperMaterial);
		System.out.println("spiral :" + noteBook2.spiral);
		System.out.println("usage :" + noteBook2.usage);
		System.out.println("coverMaterial :" + noteBook2.coverMaterial);
		System.out.println(noteBook2);
		System.out.println("\n");

		Clock clock1 = new Clock();

		System.out.println("brand :" + clock1.brand);
		System.out.println("color :" + clock1.color);
		System.out.println("price :" + clock1.price);
		System.out.println("digital :" + clock1.digital);
		System.out.println("warranty:" + clock1.warranty);
		System.out.println("type :" + clock1.type);
		System.out.println("shape :" + clock1.shape);
		System.out.println("weight :" + clock1.weight);
		System.out.println("smart :" + clock1.smart);
		System.out.println("displayType :" + clock1.displayType);
		System.out.println("batteryLife :" + clock1.batteryLife);
		System.out.println("size :" + clock1.size);
		System.out.println("material :" + clock1.material);
		System.out.println("alarm :" + clock1.alarm);
		System.out.println("timeFormat :" + clock1.timeFormat);
		System.out.println("brightnessLevel :" + clock1.brightnessLevel);
		System.out.println("accuracy :" + clock1.accuracy);
		System.out.println("origin :" + clock1.origin);
		System.out.println("waterproof :" + clock1.waterproof);
		System.out.println("usage :" + clock1.usage);
		System.out.println("powerSource :" + clock1.powerSource);
		System.out.println("buttons :" + clock1.buttons);
		System.out.println("thickness :" + clock1.thickness);
		System.out.println("mountingType :" + clock1.mountingType);
		System.out.println("silentMode :" + clock1.silentMode);
		System.out.println("design :" + clock1.design);
		System.out.println(clock1);
		System.out.println("\n");

		Clock clock2 = new Clock();

		System.out.println("brand :" + clock2.brand);
		System.out.println("color :" + clock2.color);
		System.out.println("price :" + clock2.price);
		System.out.println("digital :" + clock2.digital);
		System.out.println("warranty:" + clock2.warranty);
		System.out.println("type :" + clock2.type);
		System.out.println("shape :" + clock2.shape);
		System.out.println("weight :" + clock2.weight);
		System.out.println("smart :" + clock2.smart);
		System.out.println("displayType :" + clock2.displayType);
		System.out.println("batteryLife :" + clock2.batteryLife);
		System.out.println("size :" + clock2.size);
		System.out.println("material :" + clock2.material);
		System.out.println("alarm :" + clock2.alarm);
		System.out.println("timeFormat :" + clock2.timeFormat);
		System.out.println("brightnessLevel :" + clock2.brightnessLevel);
		System.out.println("accuracy :" + clock2.accuracy);
		System.out.println("origin :" + clock2.origin);
		System.out.println("waterproof :" + clock2.waterproof);
		System.out.println("usage :" + clock2.usage);
		System.out.println("powerSource :" + clock2.powerSource);
		System.out.println("buttons :" + clock2.buttons);
		System.out.println("thickness :" + clock2.thickness);
		System.out.println("mountingType :" + clock2.mountingType);
		System.out.println("silentMode :" + clock2.silentMode);
		System.out.println("design :" + clock2.design);
		System.out.println(clock2);
		System.out.println("\n");

		Bangle bangle1 = new Bangle();

		System.out.println("brand :" + bangle1.brand);
		System.out.println("color :" + bangle1.color);
		System.out.println("price :" + bangle1.price);
		System.out.println("adjustable :" + bangle1.adjustable);
		System.out.println("quantity:" + bangle1.quantity);
		System.out.println("material :" + bangle1.material);
		System.out.println("type :" + bangle1.type);
		System.out.println("diameter :" + bangle1.diameter);
		System.out.println("handmade :" + bangle1.handmade);
		System.out.println("design :" + bangle1.design);
		System.out.println("weight :" + bangle1.weight);
		System.out.println("thickness :" + bangle1.thickness);
		System.out.println("finish :" + bangle1.finish);
		System.out.println("stoneStudded :" + bangle1.stoneStudded);
		System.out.println("usage :" + bangle1.usage);
		System.out.println("origin :" + bangle1.origin);
		System.out.println("antique :" + bangle1.antique);
		System.out.println("size :" + bangle1.size);
		System.out.println("pattern :" + bangle1.pattern);
		System.out.println("durability :" + bangle1.durability);
		System.out.println("shinelevel :" + bangle1.shinelevel);
		System.out.println("gender :" + bangle1.gender);
		System.out.println("ecofriendly :" + bangle1.ecofriendly);
		System.out.println("occasion :" + bangle1.occasion);
		System.out.println("plating :" + bangle1.plating);
		System.out.println("collection :" + bangle1.collection);
		System.out.println(bangle1);
		System.out.println("\n");

		Bangle bangle2 = new Bangle();

		System.out.println("brand :" + bangle2.brand);
		System.out.println("color :" + bangle2.color);
		System.out.println("price :" + bangle2.price);
		System.out.println("adjustable :" + bangle2.adjustable);
		System.out.println("quantity:" + bangle2.quantity);
		System.out.println("material :" + bangle2.material);
		System.out.println("type :" + bangle2.type);
		System.out.println("diameter :" + bangle2.diameter);
		System.out.println("handmade :" + bangle2.handmade);
		System.out.println("design :" + bangle2.design);
		System.out.println("weight :" + bangle2.weight);
		System.out.println("thickness :" + bangle2.thickness);
		System.out.println("finish :" + bangle2.finish);
		System.out.println("stoneStudded :" + bangle2.stoneStudded);
		System.out.println("usage :" + bangle2.usage);
		System.out.println("origin :" + bangle2.origin);
		System.out.println("antique :" + bangle2.antique);
		System.out.println("size :" + bangle2.size);
		System.out.println("pattern :" + bangle2.pattern);
		System.out.println("durability :" + bangle2.durability);
		System.out.println("shinelevel :" + bangle2.shinelevel);
		System.out.println("gender :" + bangle2.gender);
		System.out.println("ecofriendly :" + bangle2.ecofriendly);
		System.out.println("occasion :" + bangle2.occasion);
		System.out.println("plating :" + bangle2.plating);
		System.out.println("collection :" + bangle2.collection);
		System.out.println(bangle2);
		System.out.println("\n");

		Engine engine1 = new Engine();

		System.out.println("id :" + engine1.id);
		System.out.println("company :" + engine1.company);
		System.out.println("type :" + engine1.type);
		System.out.println("horsepower :" + engine1.horsepower);
		System.out.println("fuelType :" + engine1.fuelType);
		System.out.println("isTurbo :" + engine1.isTurbo);
		System.out.println("electric :" + engine1.electric);
		System.out.println("weight :" + engine1.weight);
		System.out.println("displacement :" + engine1.displacement);
		System.out.println("torque :" + engine1.torque);
		System.out.println("cylinders :" + engine1.cylinders);
		System.out.println("origin :" + engine1.origin);
		System.out.println("rpm :" + engine1.rpm);
		System.out.println("configuration :" + engine1.configuration);
		System.out.println("availability :" + engine1.availability);
		System.out.println("isHybrid :" + engine1.isHybrid);
		System.out.println("material :" + engine1.material);
		System.out.println("automatic :" + engine1.automatic);
		System.out.println("usage :" + engine1.usage);
		System.out.println("coolingSystem :" + engine1.coolingSystem);
		System.out.println(engine1);
		System.out.println("\n");

		Engine engine2 = new Engine();

		System.out.println("id :" + engine2.id);
		System.out.println("company :" + engine2.company);
		System.out.println("type :" + engine2.type);
		System.out.println("horsepower :" + engine2.horsepower);
		System.out.println("fuelType :" + engine2.fuelType);
		System.out.println("isTurbo :" + engine2.isTurbo);
		System.out.println("electric :" + engine2.electric);
		System.out.println("weight :" + engine2.weight);
		System.out.println("displacement :" + engine2.displacement);
		System.out.println("torque :" + engine2.torque);
		System.out.println("cylinders :" + engine2.cylinders);
		System.out.println("origin :" + engine2.origin);
		System.out.println("rpm :" + engine2.rpm);
		System.out.println("configuration :" + engine2.configuration);
		System.out.println("availability :" + engine2.availability);
		System.out.println("isHybrid :" + engine2.isHybrid);
		System.out.println("material :" + engine2.material);
		System.out.println("automatic :" + engine2.automatic);
		System.out.println("usage :" + engine2.usage);
		System.out.println("coolingSystem :" + engine2.coolingSystem);
		System.out.println(engine2);
		System.out.println("\n");

		Monitor monitor1 = new Monitor();

		System.out.println("id :" + monitor1.id);
		System.out.println("brand :" + monitor1.brand);
		System.out.println("type :" + monitor1.type);
		System.out.println("refreshRate :" + monitor1.refreshRate);
		System.out.println("resolution :" + monitor1.resolution);
		System.out.println("curved :" + monitor1.curved);
		System.out.println("touch :" + monitor1.touch);
		System.out.println("weight :" + monitor1.weight);
		System.out.println("brightness :" + monitor1.brightness);
		System.out.println("responseTime :" + monitor1.responseTime);
		System.out.println("screenSize :" + monitor1.screenSize);
		System.out.println("origin :" + monitor1.origin);
		System.out.println("ports :" + monitor1.ports);
		System.out.println("aspectRatio :" + monitor1.aspectRatio);
		System.out.println("availability :" + monitor1.availability);
		System.out.println("smart :" + monitor1.smart);
		System.out.println("material :" + monitor1.material);
		System.out.println("wallMount :" + monitor1.wallMount);
		System.out.println("usage :" + monitor1.usage);
		System.out.println("panelType :" + monitor1.panelType);
		System.out.println(monitor1);
		System.out.println("\n");

		Monitor monitor2 = new Monitor();

		System.out.println("id :" + monitor2.id);
		System.out.println("brand :" + monitor2.brand);
		System.out.println("type :" + monitor2.type);
		System.out.println("refreshRate :" + monitor2.refreshRate);
		System.out.println("resolution :" + monitor2.resolution);
		System.out.println("curved :" + monitor2.curved);
		System.out.println("touch :" + monitor2.touch);
		System.out.println("weight :" + monitor2.weight);
		System.out.println("brightness :" + monitor2.brightness);
		System.out.println("responseTime :" + monitor2.responseTime);
		System.out.println("screenSize :" + monitor2.screenSize);
		System.out.println("origin :" + monitor2.origin);
		System.out.println("ports :" + monitor2.ports);
		System.out.println("aspectRatio :" + monitor2.aspectRatio);
		System.out.println("availability :" + monitor2.availability);
		System.out.println("smart :" + monitor2.smart);
		System.out.println("material :" + monitor2.material);
		System.out.println("wallMount :" + monitor2.wallMount);
		System.out.println("usage :" + monitor2.usage);
		System.out.println("panelType :" + monitor2.panelType);
		System.out.println(monitor2);
		System.out.println("\n");

		Generator generator1 = new Generator();

		System.out.println("id :" + generator1.id);
		System.out.println("brand :" + generator1.brand);
		System.out.println("type :" + generator1.type);
		System.out.println("powerOutput :" + generator1.powerOutput);
		System.out.println("fuelType :" + generator1.fuelType);
		System.out.println("portable :" + generator1.portable);
		System.out.println("automatic :" + generator1.automatic);
		System.out.println("weight :" + generator1.weight);
		System.out.println("voltage :" + generator1.voltage);
		System.out.println("frequency :" + generator1.frequency);
		System.out.println("capacity :" + generator1.capacity);
		System.out.println("origin :" + generator1.origin);
		System.out.println("runtime :" + generator1.runtime);
		System.out.println("phase :" + generator1.phase);
		System.out.println("availability :" + generator1.availability);
		System.out.println("silent :" + generator1.silent);
		System.out.println("material :" + generator1.material);
		System.out.println("inverter :" + generator1.inverter);
		System.out.println("usage :" + generator1.usage);
		System.out.println("coolingSystem :" + generator1.coolingSystem);
		System.out.println(generator1);
		System.out.println("\n");

		Generator generator2 = new Generator();

		System.out.println("id :" + generator2.id);
		System.out.println("brand :" + generator2.brand);
		System.out.println("type :" + generator2.type);
		System.out.println("powerOutput :" + generator2.powerOutput);
		System.out.println("fuelType :" + generator2.fuelType);
		System.out.println("portable :" + generator2.portable);
		System.out.println("automatic :" + generator2.automatic);
		System.out.println("weight :" + generator2.weight);
		System.out.println("voltage :" + generator2.voltage);
		System.out.println("frequency :" + generator2.frequency);
		System.out.println("capacity :" + generator2.capacity);
		System.out.println("origin :" + generator2.origin);
		System.out.println("runtime :" + generator2.runtime);
		System.out.println("phase :" + generator2.phase);
		System.out.println("availability :" + generator2.availability);
		System.out.println("silent :" + generator2.silent);
		System.out.println("material :" + generator2.material);
		System.out.println("inverter :" + generator2.inverter);
		System.out.println("usage :" + generator2.usage);
		System.out.println("coolingSystem :" + generator2.coolingSystem);
		System.out.println(generator2);
		System.out.println("\n");

		Arduino arduino1 = new Arduino();

		System.out.println("id :" + arduino1.id);
		System.out.println("boardName :" + arduino1.boardName);
		System.out.println("microcontroller :" + arduino1.microcontroller);
		System.out.println("digitalPins :" + arduino1.digitalPins);
		System.out.println("voltage :" + arduino1.voltage);
		System.out.println("wifi :" + arduino1.wifi);
		System.out.println("bluetooth :" + arduino1.bluetooth);
		System.out.println("weight :" + arduino1.weight);
		System.out.println("clockSpeed :" + arduino1.clockSpeed);
		System.out.println("memory :" + arduino1.memory);
		System.out.println("analogPins :" + arduino1.analogPins);
		System.out.println("origin :" + arduino1.origin);
		System.out.println("pwmPins :" + arduino1.pwmPins);
		System.out.println("architecture :" + arduino1.architecture);
		System.out.println("availability :" + arduino1.availability);
		System.out.println("openSource :" + arduino1.openSource);
		System.out.println("material :" + arduino1.material);
		System.out.println("usbSupport :" + arduino1.usbSupport);
		System.out.println("usage :" + arduino1.usage);
		System.out.println("connectivity :" + arduino1.connectivity);
		System.out.println(arduino1);
		System.out.println("\n");

		Arduino arduino2 = new Arduino();

		System.out.println("id :" + arduino2.id);
		System.out.println("boardName :" + arduino2.boardName);
		System.out.println("microcontroller :" + arduino2.microcontroller);
		System.out.println("digitalPins :" + arduino2.digitalPins);
		System.out.println("voltage :" + arduino2.voltage);
		System.out.println("wifi :" + arduino2.wifi);
		System.out.println("bluetooth :" + arduino2.bluetooth);
		System.out.println("weight :" + arduino2.weight);
		System.out.println("clockSpeed :" + arduino2.clockSpeed);
		System.out.println("memory :" + arduino2.memory);
		System.out.println("analogPins :" + arduino2.analogPins);
		System.out.println("origin :" + arduino2.origin);
		System.out.println("pwmPins :" + arduino2.pwmPins);
		System.out.println("architecture :" + arduino2.architecture);
		System.out.println("availability :" + arduino2.availability);
		System.out.println("openSource :" + arduino2.openSource);
		System.out.println("material :" + arduino2.material);
		System.out.println("usbSupport :" + arduino2.usbSupport);
		System.out.println("usage :" + arduino2.usage);
		System.out.println("connectivity :" + arduino2.connectivity);
		System.out.println(arduino2);
		System.out.println("\n");

		Shampoo shampoo1 = new Shampoo();

		System.out.println("id :" + shampoo1.id);
		System.out.println("brand :" + shampoo1.brand);
		System.out.println("type :" + shampoo1.type);
		System.out.println("quantity :" + shampoo1.quantity);
		System.out.println("fragrance :" + shampoo1.fragrance);
		System.out.println("antiDandruff :" + shampoo1.antiDandruff);
		System.out.println("herbal :" + shampoo1.herbal);
		System.out.println("weight :" + shampoo1.weight);
		System.out.println("phLevel :" + shampoo1.phLevel);
		System.out.println("shelfLife :" + shampoo1.shelfLife);
		System.out.println("price :" + shampoo1.price);
		System.out.println("origin :" + shampoo1.origin);
		System.out.println("rating :" + shampoo1.rating);
		System.out.println("color :" + shampoo1.color);
		System.out.println("availability :" + shampoo1.availability);
		System.out.println("organic :" + shampoo1.organic);
		System.out.println("ingredient :" + shampoo1.ingredient);
		System.out.println("sulfateFree :" + shampoo1.sulfateFree);
		System.out.println("usage :" + shampoo1.usage);
		System.out.println("packagingType :" + shampoo1.packagingType);
		System.out.println(shampoo1);
		System.out.println("\n");

		Shampoo shampoo2 = new Shampoo();

		System.out.println("id :" + shampoo2.id);
		System.out.println("brand :" + shampoo2.brand);
		System.out.println("type :" + shampoo2.type);
		System.out.println("quantity :" + shampoo2.quantity);
		System.out.println("fragrance :" + shampoo2.fragrance);
		System.out.println("antiDandruff :" + shampoo2.antiDandruff);
		System.out.println("herbal :" + shampoo2.herbal);
		System.out.println("weight :" + shampoo2.weight);
		System.out.println("phLevel :" + shampoo2.phLevel);
		System.out.println("shelfLife :" + shampoo2.shelfLife);
		System.out.println("price :" + shampoo2.price);
		System.out.println("origin :" + shampoo2.origin);
		System.out.println("rating :" + shampoo2.rating);
		System.out.println("color :" + shampoo2.color);
		System.out.println("availability :" + shampoo2.availability);
		System.out.println("organic :" + shampoo2.organic);
		System.out.println("ingredient :" + shampoo2.ingredient);
		System.out.println("sulfateFree :" + shampoo2.sulfateFree);
		System.out.println("usage :" + shampoo2.usage);
		System.out.println("packagingType :" + shampoo2.packagingType);
		System.out.println(shampoo2);
		System.out.println("\n");

		Iron iron1 = new Iron();

		System.out.println("id :" + iron1.id);
		System.out.println("brand :" + iron1.brand);
		System.out.println("type :" + iron1.type);
		System.out.println("power :" + iron1.power);
		System.out.println("color :" + iron1.color);
		System.out.println("steam :" + iron1.steam);
		System.out.println("autoOff :" + iron1.autoOff);
		System.out.println("weight :" + iron1.weight);
		System.out.println("voltage :" + iron1.voltage);
		System.out.println("temperature :" + iron1.temperature);
		System.out.println("price :" + iron1.price);
		System.out.println("origin :" + iron1.origin);
		System.out.println("warranty :" + iron1.warranty);
		System.out.println("soleplate :" + iron1.soleplate);
		System.out.println("availability :" + iron1.availability);
		System.out.println("ecoMode :" + iron1.ecoMode);
		System.out.println("material :" + iron1.material);
		System.out.println("cordless :" + iron1.cordless);
		System.out.println("usage :" + iron1.usage);
		System.out.println("cordType :" + iron1.cordType);
		System.out.println(iron1);
		System.out.println("\n");

		Iron iron2 = new Iron();

		System.out.println("id :" + iron2.id);
		System.out.println("brand :" + iron2.brand);
		System.out.println("type :" + iron2.type);
		System.out.println("power :" + iron2.power);
		System.out.println("color :" + iron2.color);
		System.out.println("steam :" + iron2.steam);
		System.out.println("autoOff :" + iron2.autoOff);
		System.out.println("weight :" + iron2.weight);
		System.out.println("voltage :" + iron2.voltage);
		System.out.println("temperature :" + iron2.temperature);
		System.out.println("price :" + iron2.price);
		System.out.println("origin :" + iron2.origin);
		System.out.println("warranty :" + iron2.warranty);
		System.out.println("soleplate :" + iron2.soleplate);
		System.out.println("availability :" + iron2.availability);
		System.out.println("ecoMode :" + iron2.ecoMode);
		System.out.println("material :" + iron2.material);
		System.out.println("cordless :" + iron2.cordless);
		System.out.println("usage :" + iron2.usage);
		System.out.println("cordType :" + iron2.cordType);
		System.out.println(iron2);
		System.out.println("\n");

		Stand stand1 = new Stand();

		System.out.println("id :" + stand1.id);
		System.out.println("brand :" + stand1.brand);
		System.out.println("type :" + stand1.type);
		System.out.println("height :" + stand1.height);
		System.out.println("color :" + stand1.color);
		System.out.println("adjustable :" + stand1.adjustable);
		System.out.println("foldable :" + stand1.foldable);
		System.out.println("weight :" + stand1.weight);
		System.out.println("width :" + stand1.width);
		System.out.println("length :" + stand1.length);
		System.out.println("price :" + stand1.price);
		System.out.println("origin :" + stand1.origin);
		System.out.println("capacity :" + stand1.capacity);
		System.out.println("shape :" + stand1.shape);
		System.out.println("availability :" + stand1.availability);
		System.out.println("durable :" + stand1.durable);
		System.out.println("material :" + stand1.material);
		System.out.println("portable :" + stand1.portable);
		System.out.println("usage :" + stand1.usage);
		System.out.println("baseType :" + stand1.baseType);
		System.out.println(stand1);
		System.out.println("\n");

		Stand stand2 = new Stand();

		System.out.println("id :" + stand2.id);
		System.out.println("brand :" + stand2.brand);
		System.out.println("type :" + stand2.type);
		System.out.println("height :" + stand2.height);
		System.out.println("color :" + stand2.color);
		System.out.println("adjustable :" + stand2.adjustable);
		System.out.println("foldable :" + stand2.foldable);
		System.out.println("weight :" + stand2.weight);
		System.out.println("width :" + stand2.width);
		System.out.println("length :" + stand2.length);
		System.out.println("price :" + stand2.price);
		System.out.println("origin :" + stand2.origin);
		System.out.println("capacity :" + stand2.capacity);
		System.out.println("shape :" + stand2.shape);
		System.out.println("availability :" + stand2.availability);
		System.out.println("durable :" + stand2.durable);
		System.out.println("material :" + stand2.material);
		System.out.println("portable :" + stand2.portable);
		System.out.println("usage :" + stand2.usage);
		System.out.println("baseType :" + stand2.baseType);
		System.out.println(stand2);
		System.out.println("\n");
	}

}